apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-reflector-controller.fullname" . }}-manager-role
  labels:
  {{- include "cluster-reflector-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.weave.works
  resources:
  - automatedclusterdiscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.weave.works
  resources:
  - automatedclusterdiscoveries/finalizers
  verbs:
  - update
- apiGroups:
  - clusters.weave.works
  resources:
  - automatedclusterdiscoveries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-reflector-controller.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-reflector-controller
    app.kubernetes.io/part-of: cluster-reflector-controller
  {{- include "cluster-reflector-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "cluster-reflector-controller.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "cluster-reflector-controller.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'